version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7017:8080"  
    environment:
      - DefaultConnection=db=db;Database=DeveloperEvaluation;Username=postgres;Password=mysecretpassword
  
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: DeveloperEvaluation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  